# Copyright (c) 2025 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/default_targets.gni")
import("//build/templates/board.gni")
import("//build/templates/linker_script.gni")

_sysroot = exec_script("//build/scripts/get_sysroot.py",
                       [ "arm-none-eabi-gcc" ],
                       "string")

generate_linker_script("default_linker_script") {
  preprocessor = "arm-none-eabi-cpp"
  template = "//kernel/arch/arm/cortex_m/link.x"
  output = "${root_gen_dir}/link.pre.ld"
}

blueos_board("gd32e507_eval") {
  kernel_config = {
    cflags = [
      "--target=thumbv8m.main-none-eabihf",
      "--static",
      "-fshort-enums",
      "-fsigned-char",
      "-nostdlib",
      "-isystem",
      "${_sysroot}/include",
    ]
    ldflags = [
      "-nostartfiles",
      "-Wl,-gc-sections",
    ]
    rustflags = [
      "--cfg",
      "target_board=\"gd32e507_eval\"",
      "--cfg",
      "cortex_m",
      "--cfg",
      "armv8m",
      "--cfg",
      "armv8m_main",
      "--cfg",
      "has_fpu",
      "-Zemit-stack-sizes",
      "-Crelocation-model=static",
      "-Clinker=arm-none-eabi-gcc",
    ]
    foreach(item, ldflags) {
      rustflags += [ "-Clink-arg=${item}" ]
    }
  }
  app_config = {
  }

  if (debug) {
    # FIXME: Disable apps in debug build temporarily,
    # because of the size of firmware too big in debug mode.
    default = [ "//apps/shell" ]
  } else {
    default = [
      "//apps/shell",
      "//apps/example/blinky:blinky_example",
    ]
  }

  check_all = clippy_all_on_virtual_board
}
